server:
    port: 8090
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/xmen-project
        username: postgres
        password: 'admin'
